### ISSUE TITLE
Write Multiple Registers for slave not included

### ISSUE THREAD

**Issue by Freddy2es** [ClassicDIY/ModbusTool#11]
Function 0x10 (write multiple holding registers) is missing for the slave while function 0x06 (write single holding register) is there. Why? I mean, as long as you've chosen "03 Holding Register" at the "Function" section of the application, I think both functions should be available in order not to be a little bit too restricted when you're going to write registers as you are now.

**Comment by graham22** [comment]
Removed function restrictions on the ModbusSlave app
