### ISSUE TITLE
Modbus slave always returns value 0

### ISSUE THREAD

**Issue by IoTThinks** [ClassicDIY/ModbusTool#25]
Hi team,
Thanks for the lovely tool.
I suspect there is an issue in Modbus slave.
The address 4918 is 0x1336 in the communication log. So this is correct.

I did click Apply button.
However, the tool returns 00 00 instead of 12 34.
Please help to advice.
Thanks a lot.
![image](https://user-images.githubusercontent.com/29994971/225030753-c3217ade-3885-439f-a684-7c94d0d9631a.png)

**Comment by IoTThinks** [comment]
I guess the Apply button doesn't save the register value.

**Comment by bforbenny** [comment]
Hi @IoTThinks,
Have you tried start address of "4918"?

**Comment by IoTThinks** [comment]
Really.
Ok let me try later today.

**Comment by IoTThinks** [comment]
Address 4918 works!!!
