### ISSUE TITLE
Windows not completetly visible

### ISSUE THREAD

**Issue by greenscreenflicker** [ClassicDIY/ModbusTool#46]
The status window is not completely visible - please fix
![grafik](https://github.com/user-attachments/assets/d09d0760-0860-4bca-8623-69a743d04ed9)

**Comment by longzheng** [comment]
@graham22 I noticed at least 2 people complaining about the window size not fitting their monitor https://github.com/ClassicDIY/ModbusTool/issues/33

I know I recently made the change to fix the window size, but I just realised it's also possible to make the window scrollable. Do you think that's a good idea? If so I'll do a PR.

**Comment by greenscreenflicker** [comment]
that would solve my problem
