### ISSUE TITLE
ModbusTool Slave : Single and Multi Registers

### ISSUE THREAD

**Issue by AceAutomation** [ClassicDIY/ModbusTool#9]
Greetings,
There is probably a bug with the Modbus Slave Tool. We are not sure.
It seems that single write to the software is not standard Modbus, the feedback code is wrong.
And multi write got no response.
Can you confirm ?
Thanks
![multi register](https://user-images.githubusercontent.com/38076506/42996454-ea10c5d8-8c13-11e8-8f19-4fd28c4e98f5.jpg)
![single register](https://user-images.githubusercontent.com/38076506/42996455-ea3e965c-8c13-11e8-9428-913983139e08.jpg)

**Comment by graham22** [comment]
Removed function restriction in Slave app
